coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 80%
        threshold: 5%

ignore:
  - "tests/"
  - "database/"
  - "public/"
  - "bootstrap/"
  - "config/"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false